-- MySQL Script generated by MySQL Workbench
-- Fri Jun 11 09:29:26 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Spotify
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Spotify
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Spotify` DEFAULT CHARACTER SET utf8 ;
USE `Spotify` ;

-- -----------------------------------------------------
-- Table `Spotify`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `Usuariocol` VARCHAR(100) NULL,
  `FechaRegistro` DATE NULL,
  `Tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`Usuario_normal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`Usuario_normal` (
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`Usuario_idUsuario`),
  CONSTRAINT `fk_Usuario_normal_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `Spotify`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`UsuarioPremium`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`UsuarioPremium` (
  `Usuario_normal_Usuario_idUsuario` INT NOT NULL,
  `FechaVip` DATE NOT NULL,
  PRIMARY KEY (`Usuario_normal_Usuario_idUsuario`, `FechaVip`),
  INDEX `fk_UsuarioPremium_Usuario_normal1_idx` (`Usuario_normal_Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_UsuarioPremium_Usuario_normal1`
    FOREIGN KEY (`Usuario_normal_Usuario_idUsuario`)
    REFERENCES `Spotify`.`Usuario_normal` (`Usuario_idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`Artista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`Artista` (
  `Usuario_idUsuario` INT NOT NULL,
  `Seguidores` INT NULL,
  PRIMARY KEY (`Usuario_idUsuario`),
  CONSTRAINT `fk_Artista_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `Spotify`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`Álbun`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`Álbun` (
  `idÁlbun` INT NOT NULL,
  `nombre` VARCHAR(100) NULL,
  `Artista_idArtista` INT NOT NULL,
  `Artista_Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idÁlbun`),
  INDEX `fk_Álbun_Artista1_idx` (`Artista_Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Álbun_Artista1`
    FOREIGN KEY (`Artista_Usuario_idUsuario`)
    REFERENCES `Spotify`.`Artista` (`Usuario_idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`Canción`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`Canción` (
  `Nombre` VARCHAR(100) NOT NULL,
  `genero` VARCHAR(45) NULL,
  `Álbun_idÁlbun` INT NOT NULL,
  `Artista_idArtista` INT NOT NULL,
  PRIMARY KEY (`Nombre`, `Álbun_idÁlbun`),
  INDEX `fk_Canción_Álbun1_idx` (`Álbun_idÁlbun` ASC) VISIBLE,
  CONSTRAINT `fk_Canción_Álbun1`
    FOREIGN KEY (`Álbun_idÁlbun`)
    REFERENCES `Spotify`.`Álbun` (`idÁlbun`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`Playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`Playlist` (
  `idPlaylist` INT NOT NULL,
  `Nombre` VARCHAR(100) NULL,
  PRIMARY KEY (`idPlaylist`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`Lista_canciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`Lista_canciones` (
  `Playlist_idPlaylist` INT NOT NULL,
  `Canción_Nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Playlist_idPlaylist`, `Canción_Nombre`),
  INDEX `fk_Playlist_has_Canción_Canción1_idx` (`Canción_Nombre` ASC) VISIBLE,
  INDEX `fk_Playlist_has_Canción_Playlist_idx` (`Playlist_idPlaylist` ASC) VISIBLE,
  CONSTRAINT `fk_Playlist_has_Canción_Playlist`
    FOREIGN KEY (`Playlist_idPlaylist`)
    REFERENCES `Spotify`.`Playlist` (`idPlaylist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Playlist_has_Canción_Canción1`
    FOREIGN KEY (`Canción_Nombre`)
    REFERENCES `Spotify`.`Canción` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`Playlist_has_Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`Playlist_has_Usuario` (
  `Playlist_idPlaylist` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`Playlist_idPlaylist`, `Usuario_idUsuario`),
  INDEX `fk_Playlist_has_Usuario_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  INDEX `fk_Playlist_has_Usuario_Playlist1_idx` (`Playlist_idPlaylist` ASC) VISIBLE,
  CONSTRAINT `fk_Playlist_has_Usuario_Playlist1`
    FOREIGN KEY (`Playlist_idPlaylist`)
    REFERENCES `Spotify`.`Playlist` (`idPlaylist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Playlist_has_Usuario_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `Spotify`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`Colabora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`Colabora` (
  `Canción_Nombre` VARCHAR(100) NOT NULL,
  `Canción_Álbun_idÁlbun` INT NOT NULL,
  `Artista_Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`Canción_Nombre`, `Canción_Álbun_idÁlbun`, `Artista_Usuario_idUsuario`),
  INDEX `fk_Canción_has_Artista_Artista1_idx` (`Artista_Usuario_idUsuario` ASC) VISIBLE,
  INDEX `fk_Canción_has_Artista_Canción1_idx` (`Canción_Nombre` ASC, `Canción_Álbun_idÁlbun` ASC) VISIBLE,
  CONSTRAINT `fk_Canción_has_Artista_Canción1`
    FOREIGN KEY (`Canción_Nombre` , `Canción_Álbun_idÁlbun`)
    REFERENCES `Spotify`.`Canción` (`Nombre` , `Álbun_idÁlbun`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Canción_has_Artista_Artista1`
    FOREIGN KEY (`Artista_Usuario_idUsuario`)
    REFERENCES `Spotify`.`Artista` (`Usuario_idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
